baseURL = 'https://zisu-build.github.io/'
languageCode = 'ko-kr'
title = 'ðŸ‘‹ Build Something'
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowToc = true
  defaultTheme = "auto" 

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10